### ISSUE TITLE
BEM'ify

### ISSUE THREAD

**Issue by maraisr** [sierra-library/sierra#11]
Thinking as a Version 2, I'll [BEMify](http://mathayward.com/modular-css-with-sass-and-bem/) the sass to be just another supporter of the SASS movement.. What you guys thinking? Think it'll leave even a lower footprint..

**Comment by JoanClaret** [comment]
Yeah. This is a big change but i'd love to do it.

**Comment by GriNAME** [comment]
It's a good idea!

**Comment by marnen** [comment]
Too bad. I was looking at Sierra for a new project, but if it's going in the direction of BEM, then no way. (I despise BEM because I think it poorly reinvents features that CSS already provides.)

**Comment by maraisr** [comment]
@marnen  thank you for your input, but I mean  what do you do in the case of `.button` and `.button .inner` and haveing a `.block .inner` won't those two `.inner's` cause some conflict? You'd probably end up writing more reset CSS than actual styles.

Isn't `.button__inner` much nicer and gives you 100% piece of mind that conflicts won't occur... Not to mention that scalability of the CSS. Pure CSS is fine for like small one-man projects, but for anything that involves a team and a project that spans across multiple months - then yeah, BEM is amazing.

**Comment by marnen** [comment]
@maraisr:
I didn't want to derail this discussion, but since you asked...
> what do you do in the case of `.button` and `.button .inner` and haveing a `.block .inner` won't those two .inner's cause some conflict?

Not unless you've totally mismanaged your CSS. If you keep your selectors at the proper level of specificity,  they don't conflict at all. If you disagree, can you be more specific with the type of problem you have in mind?

> Isn't `.button__inner` much nicer

No, because it repeats information that should not have to be repeated, and because it (poorly) duplicates what the CSS cascade will do if you let it. Instead of `.button__inner`, your selector should be `.button .inner` (which will not conflict with `.block .inner` at all). The BEM naming also inhibits reuse. 

Also, if I see BEM naming in CSS that I'm maintaining, I immediately have to assume that whoever wrote it doesn't know how to manage CSS selectors and cascading properly. That means I now have to wonder about what *else* they don't understand about CSS. :)

> Not to mention that scalability of the CSS. Pure CSS is fine for like small one-man projects, but for anything that involves a team and a project that spans across multiple months - then yeah, BEM is amazing.

My experience, and that of my colleagues on large projects, has been the exact opposite. BEM may be admissible—just—on a small project, but it quickly gets very unpleasant on a site of any size. At my last job , we had a design shop that delivered us some HTML using Bem. The developers and in-house designers were _unanimously_ in support of removing the BEM naming in favor of just using the cascade properly. 

If you are interested in discussing CSS organization in greater depth (probably not in this thread), I'd be happy to.

**Comment by maraisr** [comment]
I don't know about that... Am a pretty experienced front-end developer and having worked for some pretty large organisations and will stand by my original statement, BEM is powerful. No discussion needed man.

**Comment by brianbower** [comment]
@marnen of course if you use "CSS selectors and cascading properly" you won't have problems. That's like saying "If you jump out of a plane and put your parachute on correctly, you should have no problems". The point is that BEM is supposed to make managing CSS easier, not that it does something that isn't part of CSS.

Nontheless, I think it's a bad idea to include this methodology in a library, and should have been discussed before making a decision. Let the user decide how they want to manage their CSS.
