### ISSUE TITLE
Warning with badge key name

### ISSUE THREAD

**Issue by brianbower** [sierra-library/sierra#30]
There's a warning when I compile, which isn't an issue but can easily be resolved to remove that warning. For the badges, the compiler doesn't like how the key `gray` in `_variables.scss` is being interpolated. An easy fix is to simply scroll down to `$badges-color-map` and rename `gray` to something else, such as `light`. Then of course we'll have to begin using that new class (`badge-light`) if we want to use that grey badge.

The warning is bringing attention to the fact that the color may be converted to another value such as hex, but in this case, I don't believe that will happen since we're just grabbing a key name in `_badges.scss`.

**Comment by maraisr** [comment]
Hello @brianbower - this is a general concern with SCSS and its compiler.. Because it doesn't quite know the context.

What we've done in the past is - use `.badge-#{$grey+''}` this'll cause the compiler to think its a string, and not a property / value, which'll not spit out the warnings.

Alternatively, you could turn off warnings in your compiler stage.. 

Mind you, are you use Ruby SASS, or the node-sass wrapper for libsass?

**Comment by brianbower** [comment]
If we plan on adding more badges and we want them to have color names, we should use your `$grey + ''` fix. Otherwise, I think we should simply rename `grey` to something else. @JoanClaret you should be able to decide how to fix this based on what we've said, now. If you want me to add the fix I can, thanks!

**Comment by maraisr** [comment]
Ultimately @brianbower its up to you how you implement the library. You can see sierra as an off the shelf product for which you use as is, or you could fork a copy and make changes to fit your needs (which we've seen in the past). 

A greater percentage of our audience use this as an off the shelf solution, and `gray` just makes sense to them to use, rather than as you put it `light`... 

In your case i'd suggest `git clone`'ing the repo, and making the changes that suit your specific need, in the sense of creating more badges and alike..

Im quite happy to consult with @JoanClaret as to what his feel is, but im sure he'd agree with me on this one.

**Comment by JoanClaret** [comment]
Hi guys, 
Since this is the only badge we have with a color in the class name, i think we should rename it in to `badge-light`. In my opinion, this will give more consistency to the badges naming.

```primary:              $brand-primary ```
  ```secondary:            $brand-secondary ```
```  dark:                 $brand-dark ```
```  gray:                 $gray```
```  success:              $color-success```
```  error:                $color-error```
  ```warning:              $color-warning```

**Comment by brianbower** [comment]
@maraisr I'm unsure what you mean. Why would you keep a feature that generates warnings? I suggested using your fix, if everyone prefers using `grey`. Of course I'm going to fork and add my own changes. This was just a quick suggestion to help the project out, in case anyone else was wondering why they were getting warnings.

Anyways, thanks @JoanClaret, sounds good!

**Comment by brianbower** [comment]
#30
